# Sidebar navigation

- label: "Vorbereitung"
  items:
    - label: 'Installieren von Java'
      link: "/preparation/installation-java"
    - label: 'Installieren von IntelliJ'
      link: "/preparation/installation-intellij"
- label: "Hausübungen"
  items:
    - label: "Herunterladen und Importieren"
      link: "/exercises/download-import"
    - label: "Bearbeiten"
      link: "/exercises/edit"
    - label: "Exportieren und Hochladen"
      link: "/exercises/export-upload"
    - label: "Nicht-Unterstützte IDEs"
      link: "/exercises/download-import-unsupported"
